const std = @import("std");
const Response = @import("../http/response.zig").Response;

/// RFC 7807 Problem Details for HTTP APIs.
///
/// Provides a standardised way to carry machine-readable error details in an
/// HTTP response body. The Content-Type is set to `application/problem+json`
/// and the JSON payload includes the members defined in RFC 7807 Section 3.1.
pub const ProblemDetail = struct {
    /// A URI reference that identifies the problem type (default "about:blank").
    type_uri: []const u8 = "about:blank",
    /// A short, human-readable summary of the problem type.
    title: []const u8,
    /// The HTTP status code generated by the origin server for this occurrence.
    status: u16,
    /// A human-readable explanation specific to this occurrence of the problem.
    detail: ?[]const u8 = null,
    /// A URI reference that identifies the specific occurrence of the problem.
    instance: ?[]const u8 = null,
};

/// Create a `Response` from a `ProblemDetail`.
///
/// The response body is a JSON object with the RFC 7807 members (`type`,
/// `title`, `status`, and optionally `detail` / `instance`).  The
/// `Content-Type` header is set to `application/problem+json` and the HTTP
/// status code is derived from `problem.status`.
pub fn problemResponse(allocator: std.mem.Allocator, problem: ProblemDetail) !Response {
    var response = try Response.json(allocator, .{
        .type = problem.type_uri,
        .title = problem.title,
        .status = problem.status,
        .detail = problem.detail,
        .instance = problem.instance,
    });
    // Override the default application/json content-type.
    response.content_type = "application/problem+json";
    response = response.withStatus(statusFromU16(problem.status));
    return response;
}

// ----- convenience constructors -----

pub fn notFound(allocator: std.mem.Allocator, detail: ?[]const u8) !Response {
    return problemResponse(allocator, .{
        .title = "Not Found",
        .status = 404,
        .detail = detail,
    });
}

pub fn badRequest(allocator: std.mem.Allocator, detail: ?[]const u8) !Response {
    return problemResponse(allocator, .{
        .title = "Bad Request",
        .status = 400,
        .detail = detail,
    });
}

pub fn unauthorized(allocator: std.mem.Allocator, detail: ?[]const u8) !Response {
    return problemResponse(allocator, .{
        .title = "Unauthorized",
        .status = 401,
        .detail = detail,
    });
}

pub fn forbidden(allocator: std.mem.Allocator, detail: ?[]const u8) !Response {
    return problemResponse(allocator, .{
        .title = "Forbidden",
        .status = 403,
        .detail = detail,
    });
}

pub fn conflict(allocator: std.mem.Allocator, detail: ?[]const u8) !Response {
    return problemResponse(allocator, .{
        .title = "Conflict",
        .status = 409,
        .detail = detail,
    });
}

pub fn unprocessableEntity(allocator: std.mem.Allocator, detail: ?[]const u8) !Response {
    return problemResponse(allocator, .{
        .title = "Unprocessable Entity",
        .status = 422,
        .detail = detail,
    });
}

pub fn internalServerError(allocator: std.mem.Allocator, detail: ?[]const u8) !Response {
    return problemResponse(allocator, .{
        .title = "Internal Server Error",
        .status = 500,
        .detail = detail,
    });
}

// ----- helpers -----

fn statusFromU16(code: u16) std.http.Status {
    return @enumFromInt(code);
}

// ----- unit tests -----

test "problemResponse produces correct content-type and body" {
    const alloc = std.testing.allocator;
    var res = try problemResponse(alloc, .{
        .title = "Not Found",
        .status = 404,
        .detail = "no such item",
    });
    defer res.deinit(alloc);

    try std.testing.expectEqualStrings("application/problem+json", res.content_type);
    try std.testing.expectEqual(std.http.Status.not_found, res.status);
    try std.testing.expect(std.mem.indexOf(u8, res.body, "\"title\":\"Not Found\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, res.body, "\"status\":404") != null);
    try std.testing.expect(std.mem.indexOf(u8, res.body, "\"detail\":\"no such item\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, res.body, "\"type\":\"about:blank\"") != null);
}

test "convenience notFound constructor" {
    const alloc = std.testing.allocator;
    var res = try notFound(alloc, "resource missing");
    defer res.deinit(alloc);

    try std.testing.expectEqual(std.http.Status.not_found, res.status);
    try std.testing.expectEqualStrings("application/problem+json", res.content_type);
    try std.testing.expect(std.mem.indexOf(u8, res.body, "\"detail\":\"resource missing\"") != null);
}

test "convenience badRequest constructor" {
    const alloc = std.testing.allocator;
    var res = try badRequest(alloc, "invalid input");
    defer res.deinit(alloc);

    try std.testing.expectEqual(std.http.Status.bad_request, res.status);
}

test "convenience unauthorized constructor" {
    const alloc = std.testing.allocator;
    var res = try unauthorized(alloc, null);
    defer res.deinit(alloc);

    try std.testing.expectEqual(std.http.Status.unauthorized, res.status);
}

test "convenience internalServerError constructor" {
    const alloc = std.testing.allocator;
    var res = try internalServerError(alloc, "something broke");
    defer res.deinit(alloc);

    try std.testing.expectEqual(std.http.Status.internal_server_error, res.status);
    try std.testing.expect(std.mem.indexOf(u8, res.body, "\"detail\":\"something broke\"") != null);
}

test "null detail and instance are serialized" {
    const alloc = std.testing.allocator;
    var res = try problemResponse(alloc, .{
        .title = "Conflict",
        .status = 409,
    });
    defer res.deinit(alloc);

    try std.testing.expectEqual(std.http.Status.conflict, res.status);
    // null fields should appear as null in JSON
    try std.testing.expect(std.mem.indexOf(u8, res.body, "\"detail\":null") != null);
    try std.testing.expect(std.mem.indexOf(u8, res.body, "\"instance\":null") != null);
}

test "custom type_uri is included" {
    const alloc = std.testing.allocator;
    var res = try problemResponse(alloc, .{
        .type_uri = "https://example.com/probs/out-of-credit",
        .title = "Out of Credit",
        .status = 403,
        .detail = "Your current balance is 30, but that costs 50.",
        .instance = "/account/12345/msgs/abc",
    });
    defer res.deinit(alloc);

    try std.testing.expect(std.mem.indexOf(u8, res.body, "\"type\":\"https://example.com/probs/out-of-credit\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, res.body, "\"instance\":\"/account/12345/msgs/abc\"") != null);
}
